feat(toggle-button): create toggle-button component
cft-group/elephas-react pull request #303
Opened 2021-01-15 12:36 UTC by EkaterinaMozheiko

Closes #300

2021-01-18 09:27 UTC, apust requested changes
Оставил пару комментариев. Готов согласится с предложенным решением, если будут ответы на эти вопросы.

2021-01-18 09:27 UTC, apust commented on src/packages/core/src/toggle-button/ToggleButton.tsx
> +const Item = ({ item, isSelected, onClick }: ItemProps) => (
Может, стоит вынести это в отдельный файл? По аналогии с Tab/Tabs, чтобы было единообразие между компонентами. А интерфейс, соответственно, в `types.ts`. Тогда все типы можно будет посмотреть в одном файле.

2021-01-18 09:27 UTC, apust commented on src/packages/core/src/toggle-button/types.ts
> +export type ToggleButtonItemValue = string | string[] | null;
Есть ощущение, как будто мы слишком неявно позволяем выбирать между `select single` и `select multiple` через тип значения.

2021-01-18 10:10 UTC, EkaterinaMozheiko commented on src/packages/core/src/toggle-button/types.ts
> +export type ToggleButtonItemValue = string | string[] | null;
Но с флагом у нас получается два источника истины. Еще один вариант: все-таки добавить флаг, но задать более строгую типизацию: {multiple: true, value: string[]} или {multiple: false, value: string}

2021-01-18 11:49 UTC, EkaterinaMozheiko commented on src/packages/core/src/toggle-button/ToggleButton.tsx
> +const Item = ({ item, isSelected, onClick }: ItemProps) => (
Tab и Tabs являются независимыми компонентами (даже экспортируются оба наружу), а Item нельзя использовать отдельно от ToggleButton. По сути я просто вынесла кусок логики из ToggleButton в Item. Пользователь не должен знать, что вообще такой компонент существует. Все нужные пропсы ему и так видны в types.ts

2021-01-19 07:10 UTC, apust commented on src/packages/core/src/toggle-button/types.ts
> +export type ToggleButtonItemValue = string | string[] | null;
Мне нравится вариант с более строгой типизацией.

2021-01-19 07:12 UTC, apust commented on src/packages/core/src/toggle-button/ToggleButton.tsx
> +const Item = ({ item, isSelected, onClick }: ItemProps) => (
> Tab и Tabs являются независимыми компонентами (даже экспортируются оба наружу), а Item нельзя использовать отдельно от ToggleButton

`Tab` тоже без обёртки в `Tabs` смысла имеет мало. Про типы посмотрел ещё раз: да, всё ок, фигню написал в прошлый раз.

2021-01-19 14:13 UTC, apust commented
Давай сделаем все изменения в одном коммите, иначе в чейнджлоге будет странная строчка.

В данный момент падают тесты сборки пакета и сторибука, ошибки вроде:

```
src/toggle-button/ToggleButton.tsx(36,14): error TS4023: Exported variable 'ToggleButton' has or is using
name 'MultipleValue' from external module  "/home/runner/work/elephas-react/elephas-react/src/packages/core/
src/toggle-button/types" but cannot be named.
```

2021-01-20 06:07 UTC, apust approved these changes
👍

2021-01-20 06:31 UTC, merged