Add icons prop  to component Input
cft-group/elephas-react pull request #7
Opened 2020-08-07 05:15 UTC by Yakutoc

## Improve types inference

### Мотивация:

Из-за того, что раньше для `TextareaHTMLAttributes` и  всех `EventHandler`  был указан  тип `HTMLElement`

то для соответствующих `props` `types inference` работал неправильно, например

```ts
onChange={(event) => {}}

typeof event => ChangeEvent<HTMLElement> 
```  

что в свою очередь приводило к принудительному кастингу типов в  `eventHandler` на стороне разработчика использующего наш компонент  

```ts
onChange={(event: ChangeEvent<HTMLInputElement>) => {}}
```
 
так как  

```ts
error: Property 'value' does not exist on type 'EventTarget & HTMLElement'.
```

### Что я сделал:

расширил имеющиеся `types` и добавил `generic` для `types`  `AbstractInput` и `BaseInputProps`;

## Add icons props

2020-08-07 06:20 UTC, EkaterinaMozheiko commented on src/packages/core/src/base-input/BaseInput.tsx
> +         }
съехала скобка

2020-08-07 06:20 UTC, EkaterinaMozheiko commented on src/packages/core/src/input/Input.tsx
> +      <BaseInput <InputHTMLAttributes<HTMLInputElement>> {...rest}>
А без этого приведения ругается?

2020-08-07 06:31 UTC, Yakutoc commented on src/packages/core/src/input/Input.tsx
> +      <BaseInput <InputHTMLAttributes<HTMLInputElement>> {...rest}>
@EkaterinaMozheiko 
 
Спасибо за комментарий. =) 

Проверил. Все корректно. Сейчас удалю за ненадобностью.

2020-08-07 06:40 UTC, EkaterinaMozheiko approved these changes

2020-08-10 03:19 UTC, apust requested changes

2020-08-10 03:19 UTC, apust commented on src/packages/core/src/base-input/BaseInput.tsx
> +        </div>
Если у нас нет иконки, то и оборачивающий её `div` в DOM рендерить незачем.

```
{ icons && <div className="_e_input__icon"> ... }
```

2020-08-10 03:40 UTC, apust commented
@Yakutoc, поменяй, пожалуйста, версию `@elephas/core` и `@elephas/layout` на [`1.0.0-beta.14`](https://github.com/cft-group/elephas/releases/tag/v1.0.0-beta.14) в `package.json`, `src/packages/core/package.json` и `src/packages/layout/package.json`.

Я убрал в 14 бете размер иконки, чтобы не ломалась вёрстка, если передаём больше одной иконки.

2020-08-10 06:56 UTC, apust approved these changes

2020-08-10 07:07 UTC, apust requested changes

2020-08-10 07:07 UTC, apust commented on src/packages/core/package.json
> +  "version": "1.0.0-beta.14",
Версию пакета устанавливает lerna при релизе через CI, не надо её менять вручную.

2020-08-10 07:07 UTC, apust commented on src/packages/layout/package.json
> +  "version": "1.0.0-beta.14",
Версию пакета устанавливает lerna при релизе через CI, не надо её менять вручную.

2020-08-10 08:58 UTC, apust approved these changes

2020-08-10 08:58 UTC, merged